version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/openjdk:${OPENJDK_TAG}-${OPENJDK_VERSION}"
    container_name: "${APP_NAME}"
    user: sindria
    command: tail -f /dev/null
    environment:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
    hostname: "${APP_NAME}.local"
    ports:
      - "8084:8080"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_app_name:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

#  # =db
#  db:
#    image: "mysql:${MYSQL_TAG}"
#    container_name: "${APP_NAME}-db"
#    command: [ "--default-authentication-plugin=mysql_native_password" ]
#    environment:
#      - MYSQL_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${APP_DB_DATABASE}
#      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_USER=${APP_DB_USERNAME}
#      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
#    volumes:
#      - "db:/var/lib/mysql"
#    hostname: "${APP_NAME}-db.local"
#    ports:
#      - "33206:3306"
#    networks:
#      default:
#        ipv4_address: "${APP_DB_IP_ADDRESS}"
#        aliases:
#          - "${APP_NAME}-db.local"
#    #networks:
#    #  vpc_<app-name>:
#    #    ipv4_address: "${DB_IP_ADDRESS}"
#    #    aliases:
#    #      - "${APP_NAME}.local"

# =networks
networks:
  default:
    name: "vpc_xpipe"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_app_name:
#    external: true

# =volumes
#volumes:
#  db: