apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-v1-prc-orchestrator-config
  namespace: xpipe-cloud
data:
  JAVA_OPTS: "-Xmx512m"
  XPIPE_CORE_POLICIES_DB_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  XPIPE_CORE_POLICIES_DB_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  XPIPE_CORE_POLICIES_DB_GENERATE_STATISTICS: "false"
  XPIPE_CORE_POLICIES_DB_JDBC_BATCH_SIZE: "30"
  XPIPE_CORE_POLICIES_DB_JDBC_ORDER_INSERTS: "true"
  XPIPE_CORE_POLICIES_DB_JDBC_ORDER_UPDATES: "true"